# Generated by Django 3.2.7 on 2021-09-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKMDb', '0002_auto_20210908_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='critic',
        ),
    ]
